### PR TITLE
Add support of PWA (full screen app) with Window Controls Overlay.

### PR DESCRIPTION
**Pull request by corentin-soriano**
Allow teampass to open as an independent application:
image
image

Or with titlebar:
image

User can hide/unhide titlebar with this button:
image

When titlebar isn't visible, we can drag in this area to move window:
image

### CODE REVIEW

**Comment by corentin-soriano** [comment]
Rebased on master and fixed merge conflicts!

**Comment by corentin-soriano** [comment]
@nilsteampassnet do you think this can be merged?

**Comment by nilsteampassnet** [comment]
@corentin-soriano yes it can be.

**Review by nilsteampassnet — APPROVED** [review]

**Comment by nilsteampassnet** [comment]
@corentin-soriano 
I have noticed this error in the console
image
I've tried to fixed it but until now could not succeed.
Don't you have the same warnings in your web console?

**Comment by corentin-soriano** [comment]
All the teampass instances I use are on a dedicated subdomain so I have not encountered this issue.
I know how to correct this: #4390

**Pull request merged**
