### PR TITLE
New English Translation

### PR DESCRIPTION
**Pull request by qubez**
Lots of work on this, refactoring using terms and style that would be recognized and expected by English software users. Natural language is used for descriptions, with emphasis on ease of translation from English to other languages.

Only English file is modified here. Other language files with untranslated lines will be merged also.

USA English is used, as I am a US native and the language flag picture is US. UK-English spells favourite instead of favorite, and could be implemented with some clever code instead of a separate language file.

Added 'enable_language_file' => '1' to array, so that future code can be added to disable untranslated languages or language files not wanted by admin.

Added style notes as a reminder to ensure consistent language use, with translator recommendations.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/nilsteampassnet/TeamPass/pull/1484%23issuecomment-246188367%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/nilsteampassnet/TeamPass/pull/1484%23issuecomment-246188367%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Thanks.%5Cr%5CnBut%20languages%20are%20managed%20from%20%5BPoeditor%5D%28https%3A//poeditor.com/projects/view%3Fid%3D16418%29.%5Cr%5CnSo%20I%20need%20to%20import%20this%20file%20in%20Poeditor%20...%20I%20don%27t%20know%20how%2C%20but%20will%20try%20to.%22%2C%20%22created_at%22%3A%20%222016-09-11T16%3A11%3A38Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1197546%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/nilsteampassnet%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/nilsteampassnet/TeamPass/pull/1484#issuecomment-246188367'>General Comment</a></b>
- <a href='https://github.com/nilsteampassnet'></a> Thanks.
But languages are managed from [Poeditor](https://poeditor.com/projects/view?id=16418).
So I need to import this file in Poeditor ... I don't know how, but will try to.

<a href='https://www.codereviewhub.com/nilsteampassnet/TeamPass/pull/1484?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/nilsteampassnet/TeamPass/pull/1484?approve=1'></a>&nbsp;<a href='https://github.com/nilsteampassnet/TeamPass/pull/1484'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by nilsteampassnet** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/nilsteampassnet/TeamPass/pull/1484'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by nilsteampassnet** [comment]
Thanks.
But languages are managed from [Poeditor](https://poeditor.com/projects/view?id=16418).
So I need to import this file in Poeditor ... I don't know how, but will try to.

**Comment by qubez** [comment]
Thanks, sorry if I created more work for you. I'll look into learning POEditor. Hopefully it automatically merges the new English into untranslated files for you.

 The Categories (now "Custom Fields") admin tab is the last really weird UI, and might need more language strings to improve it.

**Comment by nilsteampassnet** [comment]
No problem I managed it.
The translation is very good, I'm really impressed!
Many thanks, I can imagine the work it represent.

**Comment by qubez** [comment]
I just noticed that, again, Git missed some lines. I can push another commit here, or just discover and post the lines here.

**Comment by nilsteampassnet** [comment]
As you wish, I will arrange this.

By the way, while debugging #1417, I discovered bad language strings.
Please not, that strings email_body1, email_body2 and email_body3 have been deleted and replaced by 
`'new_item_email_body' => 'Hi, <br /><br />New item \'#label\' has been created in Teampass.<br />You may access it clicking on this <a href=\'#link#\'>LINK</a>.<br/><br />Greetings.',`

**Pull request merged**
