### PR TITLE
Big XHTML Validation Fix

### PR DESCRIPTION
**Pull request by qubez**
This commit includes many fixes to get XTHML Doctype errors down to
about 10 major ones, on just 4 pages, from originally over 200 from every page of
Teampass. After also fixing an errant **&amp;** in the csrfp setting file, most pages are XHTML 1.0
compliant.

Fixes include
- matching HTML tags and proper nesting for bad or missing tags like td, label, div.
- all language file text inserted into HTML title= attribute is now sanitized to
avoid breakage (like accidentally closing attribute and writing more bad html) .
- strip bad tag nesting from _settings_anyone_can_modify_bydefault_.
- many unclosed HTML single entries closed per XHTML spec
- required tags such as _cols_ used
- hidden placeholders required inside certain elements before javascript
insertions
- alt tags for images
- more...

Unfixed:
- id tags reused within page (must be unique)
(example: result_admin_action_db_restore)
- id tags starting with numbers (2factor_auth..)
- b tags -> strong
- empty for="" tags (may have been cleared due to bad function interactions?)
- language file contents
- lots of bugs discovered during QA that had to be replicated in master
- csrfp ampersand inserted into value= (different pull w possible
solution)
- anything that may impact functions (some refactoring required to fix)

Only browser rendering is fixed, no functional changes should be
present, except things that now work as designed, uniformly across
browsers.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/nilsteampassnet/TeamPass/pull/1441%23issuecomment-242476009%22%2C%20%22https%3A//github.com/nilsteampassnet/TeamPass/pull/1441%23issuecomment-243192127%22%2C%20%22https%3A//github.com/nilsteampassnet/TeamPass/pull/1441%23issuecomment-243218982%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/nilsteampassnet/TeamPass/pull/1441%23issuecomment-242476009%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Sorry%20for%20the%20merge%20mess%2C%20trying%20to%20squash%2C%20not%20working%20so%20good%20in%20Windows%20%3A%29%5Cr%5Cn%5Cr%5CnThis%20is%20ready%20to%20go%2C%20feedback%3F%22%2C%20%22created_at%22%3A%20%222016-08-25T17%3A37%3A59Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1425520%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/qubez%22%7D%7D%2C%20%7B%22body%22%3A%20%22Hi%20%40qubez%20%5Cr%5Cn%5Cr%5CnThank%20you%20for%20your%20big%20work%20here.%5Cr%5CnI%20need%20to%20check%20this%20...%20it%20will%20take%20time%20but%20I%20want%20to%20add%20in%202.1.26%22%2C%20%22created_at%22%3A%20%222016-08-29T17%3A25%3A14Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1197546%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/nilsteampassnet%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%22%2C%20%22created_at%22%3A%20%222016-08-29T18%3A53%3A18Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1197546%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/nilsteampassnet%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/nilsteampassnet/TeamPass/pull/1441#issuecomment-242476009'>General Comment</a></b>
- <a href='https://github.com/qubez'></a> Sorry for the merge mess, trying to squash, not working so good in Windows :)
This is ready to go, feedback?
- <a href='https://github.com/nilsteampassnet'></a> Hi @qubez
Thank you for your big work here.
I need to check this ... it will take time but I want to add in 2.1.26

<a href='https://www.codereviewhub.com/nilsteampassnet/TeamPass/pull/1441?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/nilsteampassnet/TeamPass/pull/1441?approve=1'></a>&nbsp;<a href='https://github.com/nilsteampassnet/TeamPass/pull/1441'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by nilsteampassnet** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/nilsteampassnet/TeamPass/pull/1441'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by qubez** [comment]
Sorry for the merge mess, trying to squash, not working so good in Windows :)

This is ready to go, feedback?

**Comment by nilsteampassnet** [comment]
Hi @qubez 

Thank you for your big work here.
I need to check this ... it will take time but I want to add in 2.1.26

**Comment by nilsteampassnet** [comment]
:+1:

**Pull request closed without merging**
