### PR TITLE
Revert "add syslog functionality. Issue 1078."

### PR DESCRIPTION
**Pull request by nilsteampassnet**
Reverts nilsteampassnet/TeamPass#1138
<a href='#crh-start'></a><a href='#crh-data-%7B%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
<a href='https://www.codereviewhub.com/nilsteampassnet/TeamPass/pull/1141?approve=1'></a>&nbsp;<a href='https://github.com/nilsteampassnet/TeamPass/pull/1141'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by nilsteampassnet** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/nilsteampassnet/TeamPass/pull/1141'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by nilsteampassnet** [comment]
I forgot to ask about this before performing the merge.
What happens if the user has no syslog on the server?
Of what I've seen, the log will not work, can you confirm?

**Comment by nunompad** [comment]
I there the log will work. The log in the data base is done before the sendo to syslog funtion.
You can a sendo de log to any server you like juste add the server in the administrativa area.
I haven't tested this solution in a server without syslog. You can define server and português for syslog server in the administrativa area.
 If you havê any more questions. 
Tks.

**Comment by nunompad** [comment]
I simply replaced all calls to insert in the log tables by or a new function or the ones you already use and adde in the end send to syslog.
So now when you what to log anything just call the function.

**Comment by nunompad** [comment]
The functions are main.functions.php.

**Comment by nunompad** [comment]
teampass-syslog

**Pull request merged**
