### PR TITLE
Fix LDAP suffix Posix syntax

### PR DESCRIPTION
**Pull request by alemairebe**
I was facing issue with LDAP auth; did a tcpdump to see what was wrong, and I saw a double , in the binddn ; with this fix it works.

### CODE REVIEW

**Comment by nilsteampassnet** [comment]
Thank you for your PR.
LDAP is still a mystery for me ... this code (without change) works in this exact condition for a user.
I don't understand why it doesn't on yours ... 
I need to investigate here.

**Comment by alemairebe** [comment]
This is the result of a tcpdump without my patch
ldap fails
This is with the patch
ldap_ok

**Comment by nilsteampassnet** [comment]
I see what I can do to improve all cases.

Thank you for this.

**Comment by nilsteampassnet** [comment]
I did a fix for this

**Pull request closed without merging**
