### PR TITLE
Added Dockerfile, compose file and updated documentation

### PR DESCRIPTION
**Pull request by acaranta**
Hi !
As I was looking for a web password manager, and a secure one I found Teampass (so first : THANK YOU ;) )

But I needed to use it as a Docker container, to be able tu run it on several of my servers, cleanly and quickly.

I therefore took time to create the dockerfile, scripts, compose file and configuration to do just that.

I thought you might be interested in having this as an option to run Teampass, so I updated the documentation.

Hope you'lllike it (engouh to merge it anyway ;) )

PS : I saw several git repositories providing Teampass as a docker container, it seems to be indeed a request for many ;)
<a href='#crh-start'></a><a href='#crh-data-%7B%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
<a href='https://www.codereviewhub.com/nilsteampassnet/TeamPass/pull/1173?approve=1'></a>&nbsp;<a href='https://github.com/nilsteampassnet/TeamPass/pull/1173'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by nilsteampassnet** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/nilsteampassnet/TeamPass/pull/1173'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by nilsteampassnet** [comment]
Thank You for this work.
I don't have the knowledge of Docker but indeed discovered that it was often used in some repositories.
Merged it into Development branch and will be part of 2.1.25

**Comment by acaranta** [comment]
Billiant ;) thx !

**Comment by acaranta** [comment]
now what you'll be even able to do is to provide an official teampass docker image on the docker hub !
if you create an acount (free) on https://hub.docker.com and create an "automated build" for your github teampass repository, the image will be built on every commit you make ... therefore keeping your teampass up to date and available for everyone ;)
That's what I did with my fork/branch you just merged : 
https://hub.docker.com/r/acaranta/teampass/

If you need help in doing so, I'll be glad to help !

**Comment by netflash** [comment]
@acaranta I suggest that it's better to use nginx-phpfpm - this image as FROM ```richarvey/nginx-php-fpm:stable```.
You can have a look at my docker fork https://github.com/netflash/docker-teampass
and if that looks ok I gonna create a pull-request which will merge yours code and mine.

**Comment by acaranta** [comment]
@netflash I chose Apache because I know it a bit better but it might be lighter with nginx.
Now whatever the webserver chosen, I had in mind the allow the user to be able to modify the configuration (the apache-default.conf) in order to add SSL and other various things which could be neede by the user.

I have to say I'll keep using my apache version (it's a personal choice :p) ... if you feel it's better to use nginx, I won't say anything against your future PR ;) ;)

**Comment by netflash** [comment]
By using nginx-php-fpm image is easy with adding SSL.
one can add volumes
/srv/teampass/nginx/ssl:/etc/nginx/ssl
and
/srv/teampass/nginx/sites-enabled:/etc/nginx/sites-enabled

Looks like we both do not really care which web server to use. So I guess we need more votes to make the right choice :-)

Another thing that I can see right now - is the "upgrade" script in 2.1.25.0 version.
Unfortunately I haven't much time yet to figure out the best way to do the "upgradable" docker container. @acaranta Any advice ?

**Comment by acaranta** [comment]
True ... I haven't taken the upgrade process into account ... however ... as the data are stored in a volume ... it should be easy to perform the upgrade there ... while keeping settings. I'll have to check when I'll have time ;)

**Pull request closed without merging**
