### PR TITLE
Fixed LDAP functionality

### PR DESCRIPTION
**Pull request by sgrund**
Fixed LDAP Search Base editing in Settings
	Added possibility to change the ldap object class for LDAP authentification
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/sgrund%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/837179%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/nilsteampassnet/TeamPass/pull/1326%23issuecomment-225262208%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222016-06-10T18%3A37%3A41Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/837179%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/sgrund%22%7D%7D%2C%20%7B%22body%22%3A%20%22Overall%20this%20is%20a%20good%20fix%2C%20thank%20you%21%20%5Cr%5CnBut%20it%20does%20not%20show%20tip%20under%20questionmark.%20So%20please%20fix%20it%2C%20so%20admin.settings.php%20line%201620%20would%20show%20%24LANG%5B%27settings_ldap_object_class_tip%27%5D%22%2C%20%22created_at%22%3A%20%222016-06-17T08%3A01%3A44Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6266189%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tehnotronic%22%7D%7D%2C%20%7B%22body%22%3A%20%22You%27re%20right%2C%20I%20fixed%20the%20Tip.%22%2C%20%22created_at%22%3A%20%222016-06-17T17%3A24%3A36Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/837179%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/sgrund%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22processed%22%3A%20%5B%22https%3A//github.com/nilsteampassnet/TeamPass/pull/1326%23issuecomment-225262208%22%2C%20%22https%3A//github.com/nilsteampassnet/TeamPass/pull/1326%23issuecomment-226706122%22%2C%20%22https%3A//github.com/nilsteampassnet/TeamPass/pull/1326%23issuecomment-226829912%22%5D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/sgrund'></a>

- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/nilsteampassnet/TeamPass/pull/1326#issuecomment-225262208'>General Comment</a></b>
- <a href='https://github.com/sgrund'></a> :shipit:
- <a href='https://github.com/tehnotronic'></a> Overall this is a good fix, thank you!
But it does not show tip under questionmark. So please fix it, so admin.settings.php line 1620 would show $LANG['settings_ldap_object_class_tip']
- <a href='https://github.com/sgrund'></a> You're right, I fixed the Tip.

<a href='https://www.codereviewhub.com/nilsteampassnet/TeamPass/pull/1326?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/nilsteampassnet/TeamPass/pull/1326?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/nilsteampassnet/TeamPass/pull/1326?approve=0'></a>&nbsp;<a href='https://github.com/nilsteampassnet/TeamPass/pull/1326'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by nilsteampassnet** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/nilsteampassnet/TeamPass/pull/1326'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by sgrund** [comment]
:shipit:

**Comment by tehnotronic** [comment]
Overall this is a good fix, thank you! 
But it does not show tip under questionmark. So please fix it, so admin.settings.php line 1620 would show $LANG['settings_ldap_object_class_tip']

**Comment by sgrund** [comment]
You're right, I fixed the Tip.

**Comment by nilsteampassnet** [comment]
Thanks

**Pull request closed without merging**
