### PR TITLE
UI - Improve items page UX to see tree/items list and items details simultaneously.

### PR DESCRIPTION
**Pull request by corentin-soriano**
Our users regret not being able to navigate between different items without a full screen popup like in teampass 2.x.
What I propose in this PR is to display the item to the right of the tree structure which is reduced only when an item is opened and returns to its initial size afterwards.

- No change on default item view:
image

- Open an item:
image

- After closing item, the default view is reverted.

- Open item details after edit or create.
image

- Same height for tree and items list containers. Scroll in items list/tree but not on global web page:
image

- Always refresh items list / item details after edition.

- Remove this ugly and confusing empty line (issue with buttons solved thanks to fixed height):
image

- Add optional variable to change page title:
image

- Correct multiple errors when deleting item from search.

- Mouse pointer on these links:
image

- Allow select text on URL field and add copy/open buttons:
image

- Remove useless buttons:
image

- Dark/light theme:
image
image

### CODE REVIEW

**Comment by corentin-soriano** [comment]
@DobroFenix you can use the [develop branch](https://github.com/corentin-soriano/TeamPass/tree/develop) from my repository which contains all the modifications of the pull requests I made on the official project.

**Comment by corentin-soriano** [comment]
Rebased on master and fixed merge conflicts!

**Comment by nilsteampassnet** [comment]
Thank you so much
Review is in progress.
I will probably add a parameter in user's settings to provide ability to display the item detail on the right or a button directly in the items view.
I really appreciate all your hard work for this project 👍😍

**Comment by corentin-soriano** [comment]
I think we can change `#folder-tree-container` and `#items-list-container` size to 0 and `#items-details-container` size to 100% when opening Details() to switch easily between full screen item view and splited mode here:
```php
$('#folder-tree-container').removeClass('col-md-5').addClass('col-md-3');
$('#items-list-container').removeClass('col-md-7').addClass('col-md-4');
$('#items-details-container').removeClass('hidden');

```

**Comment by corentin-soriano** [comment]
I just checked with this commit: [2293767aa308655441aecbceaaeb7dac2b27957f](https://github.com/nilsteampassnet/TeamPass/pull/4273/commits/2293767aa308655441aecbceaaeb7dac2b27957f)
It works, and you can even switch modes without refreshing the page in either direction (I moved the variable out of the function and changed its value via the browser console).

It would probably be better to add a setting at the user level (stored in their profile). This way, each user can choose the mode they find most convenient.

However, I'm not sure where to add this setting, and I don't have much time right now, so I stopped at a simple variable for now.

There are quite a few small changes in this PR, so don't hesitate to ask me if you need any clarifications. I'll try to find some time to respond!

**Pull request merged**
