### PR TITLE
Fix mysqli_connect in all php files

### PR DESCRIPTION
**Pull request by Arakmar**
The merge of my previous PR (#729) seems to introduce some errors.
mysqli_connect don't take an encoding parameter. We need to set it with set_charset.
http://php.net/manual/fr/mysqli.construct.php
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/nilsteampassnet/TeamPass/pull/838%23issuecomment-68540433%22%2C%20%22https%3A//github.com/nilsteampassnet/TeamPass/pull/838%23issuecomment-68589986%22%2C%20%22https%3A//github.com/nilsteampassnet/TeamPass/pull/838%23issuecomment-68589988%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/nilsteampassnet/TeamPass/pull/838%23issuecomment-68540433%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22its%20a%20bit%20strange%20seeing%20that%20the%20mysqli_connect%20isn%27t%20handled%20by%20an%20API%5Cr%5Cnbut%20noted%20in%20every%20file.%5Cr%5CnI%27d%20propose%20introducing%20a%20database%20class%20for%20general%20usage.%5Cr%5Cn%5Cr%5CnOn%20Fri%2C%20Jan%202%2C%202015%20at%2010%3A34%20PM%2C%20Nils%20Laumaill%5Cu00e9%20%3Cnotifications%40github.com%3E%5Cr%5Cnwrote%3A%5Cr%5Cn%5Cr%5Cn%3E%20This%20pull%20request%20is%20now%20managed%20with%20CodeReviewHub.%20Refresh%5Cr%5Cn%3E%20%3Chttps%3A//github.com/nilsteampassnet/TeamPass/pull/838%3E.%5Cr%5Cn%3E%20%3C%2314aab48e5c7abd96_crh-update-none%3E%5Cr%5Cn%3E%5Cr%5Cn%3E%20%5Cu2014%5Cr%5Cn%3E%20Reply%20to%20this%20email%20directly%20or%20view%20it%20on%20GitHub%5Cr%5Cn%3E%20%3Chttps%3A//github.com/nilsteampassnet/TeamPass/pull/838%23issuecomment-68534755%3E%5Cr%5Cn%3E%20.%5Cr%5Cn%3E%22%2C%20%22created_at%22%3A%20%222015-01-02T16%3A40%3A39Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/999146%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/DavidBruchmann%22%7D%7D%2C%20%7B%22body%22%3A%20%22Correct%20...%20didn%27t%20saw%20it%21%5Cr%5CnThank%20You.%22%2C%20%22created_at%22%3A%20%222015-01-03T10%3A18%3A28Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1197546%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/nilsteampassnet%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-01-03T10%3A18%3A31Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1197546%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/nilsteampassnet%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/nilsteampassnet%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1197546%3Fv%3D3%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/nilsteampassnet'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/nilsteampassnet/TeamPass/pull/838#issuecomment-68540433'>General Comment</a></b>
- <a href='https://github.com/DavidBruchmann'></a> its a bit strange seeing that the mysqli_connect isn't handled by an API
but noted in every file.
I'd propose introducing a database class for general usage.
On Fri, Jan 2, 2015 at 10:34 PM, Nils Laumaillé <notifications@github.com>
wrote:
> This pull request is now managed with CodeReviewHub. Refresh
> <https://github.com/nilsteampassnet/TeamPass/pull/838>.
> <#14aab48e5c7abd96_crh-update-none>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nilsteampassnet/TeamPass/pull/838#issuecomment-68534755>
> .
>
- <a href='https://github.com/nilsteampassnet'></a> Correct ... didn't saw it!
Thank You.

<a href='https://www.codereviewhub.com/nilsteampassnet/TeamPass/pull/838?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/nilsteampassnet/TeamPass/pull/838?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/nilsteampassnet/TeamPass/pull/838?approve=0'></a>&nbsp;<a href='https://github.com/nilsteampassnet/TeamPass/pull/838'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by nilsteampassnet** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/nilsteampassnet/TeamPass/pull/838'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by DavidBruchmann** [comment]
its a bit strange seeing that the mysqli_connect isn't handled by an API
but noted in every file.
I'd propose introducing a database class for general usage.

**Comment by nilsteampassnet** [comment]
Correct ... didn't saw it!
Thank You.

**Comment by nilsteampassnet** [comment]
:shipit:

**Pull request closed without merging**
