### PR TITLE
Update table creation with primary keys

### LINKED ISSUE #2020: Mysql error with Percona XtraDB and pxc_strict_mode
With Percona XtraDB and pxc_strict_mode enabled it won't insert anything into tables that don't have indexes defined.

```
2017-11-17T09:20:22.519783Z 8 [ERROR] WSREP: Percona-XtraDB-Cluster prohibits use of DML command on a table (teampass._install) without an explicit primary key with pxc_strict_mode = ENFORCING or MASTER
```

Can the tables be modified to have at least a primary key?

### PR DESCRIPTION
**Pull request by electrical**
This adds the required Primary Keys to all tables.

closes #2020

### CODE REVIEW

**Comment by electrical** [comment]
Double checking that the patch works. Please don't merge yet :-)

**Comment by electrical** [comment]
The patch doesn't seem to work. As soon as I use it, the installation works fine but after that I get a blank screen with a very long string that changes with each refresh.
In the apache error log it complains that my $_SESSION['key'] does not exist.
Will do some more work on this.

**Comment by electrical** [comment]
Just a quick update. Found some issues with my Patch and been fixing it along the way. Should have an update pretty soon.

**Comment by electrical** [comment]
@nilsteampassnet This should be in a good shape now for you to check. I've used this on my fresh install and works pretty good so far.

**Comment by electrical** [comment]
@nilsteampassnet would you be able to have a look at this? I think it should be ready to be merged.

**Comment by nilsteampassnet** [comment]
I have also improved this part regarding indexes and primary keys.
As used in test for a while, I will commit the changes.
They are quite similars to the one proposed in this PR.

**Comment by electrical** [comment]
Ah cool. thank you!

**Comment by electrical** [comment]
Closing as most/all issues have been solved in other commits. Thank you!

**Pull request closed without merging**
